### ISSUE TITLE
HTTPS Certificate

### ISSUE THREAD

**Issue by datapythonista** [PyDataLondon/pydatalondon.github.io#26]
Looks like we've got a hack in the london.pydata.org domain configuration to make the https of the domain work. It shouldn't be needed, and the ssl should just work if you generate a ssl certificate in the GitHub pages configuration and your force https.

I had to undo the hack, so now the domain complains about the certificate. Can you take care of the above, or give me admin permission to this repo to fix it myself? Thank you!

**Comment by kynan** [comment]
Gave you access.

**Comment by datapythonista** [comment]
Thanks! I forced https and regenerated the certificate, everything working fine now.
